<?php
/**
 * @var $block \SmartOSC\OrderManagement\Block\Adminhtml\Order\View\Tab\CustomTab
 */
?>

<div class="fieldset-wrapper order-information">
    <div class="fieldset-wrapper-title">
       <span class="title"><?php /* @escapeNotVerified */
           echo __('Custom Information for new tab') ?></span>
    </div>
    <table class="admin__table-secondary">
        <tbody>
        <?php echo $block->getChildHtml(); ?>
        <tr>
            <th><?php /* @escapeNotVerified */
                echo __('Order ID :') ?></th>
            <td><?= $block->getOrderIncrementId(); ?></td>
        </tr>
        <tr>
            <th><?php /* @escapeNotVerified */
                echo __('Customer SendEmail :') ?></th>
            <td><?= $block->getCustomerEmail(); ?></td>
        </tr>
        </tbody>
    </table>
</div>
